"""Utility functions."""

from utils.text import (
    clean_extracted_text,
    count_tokens_estimate,
    extract_error_codes,
    extract_model_numbers,
    extract_section_headers,
    format_citations,
    highlight_keywords,
    normalize_text,
    split_into_sentences,
    truncate_text,
)
from utils.validation import (
    ValidationError,
    sanitize_filename,
    validate_brand,
    validate_date_range,
    validate_email,
    validate_file_extension,
    validate_in_list,
    validate_model_number,
    validate_numeric_range,
    validate_pagination,
    validate_required,
    validate_string_length,
    validate_uuid,
)
from utils.hashing import (
    chunk_fingerprint,
    content_fingerprint,
    generate_cache_key,
    hash_dict,
    hash_file,
    hash_file_stream,
    hash_text,
    short_hash,
    verify_file_hash,
)

__all__ = [
    # Text utilities
    "clean_extracted_text",
    "count_tokens_estimate",
    "extract_error_codes",
    "extract_model_numbers",
    "extract_section_headers",
    "format_citations",
    "highlight_keywords",
    "normalize_text",
    "split_into_sentences",
    "truncate_text",
    # Validation
    "ValidationError",
    "sanitize_filename",
    "validate_brand",
    "validate_date_range",
    "validate_email",
    "validate_file_extension",
    "validate_in_list",
    "validate_model_number",
    "validate_numeric_range",
    "validate_pagination",
    "validate_required",
    "validate_string_length",
    "validate_uuid",
    # Hashing
    "chunk_fingerprint",
    "content_fingerprint",
    "generate_cache_key",
    "hash_dict",
    "hash_file",
    "hash_file_stream",
    "hash_text",
    "short_hash",
    "verify_file_hash",
]
